# Generated by Django 3.1.2 on 2020-10-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
