# Generated by Django 3.1.2 on 2020-10-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201019_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
