# Generated by Django 3.1.2 on 2020-10-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage', to='questions.question')),
            ],
        ),
    ]
