# Generated by Django 3.1.2 on 2020-10-26 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20201025_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='descrpition',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
