# Generated by Django 3.1.2 on 2020-10-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_descrpition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='descrpition',
            new_name='description',
        ),
    ]
