# Generated by Django 3.1.2 on 2020-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201026_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_to_prepare',
            field=models.CharField(default=15, max_length=10),
            preserve_default=False,
        ),
    ]
