# Generated by Django 3.1.2 on 2020-10-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_time_to_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='people',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
